CREATE TABLE [dbo].[LoggingsTest] (
    [ID]     INT          NULL,
    [FNAME]  VARCHAR (50) NULL,
    [LNAME]  VARCHAR (50) NULL,
    [SALARY] MONEY        NULL
);


GO
  CREATE TRIGGER T1 ON LoggingsTest
  AFTER INSERT
  AS
  BEGIN
  SELECT * FROM INSERTED
  END
GO
 CREATE TRIGGER T2 ON LoggingsTest
AFTER DELETE
AS
BEGIN
SELECT * FROM DELETED
END
GO
CREATE TRIGGER T3 ON LoggingsTest
AFTER UPDATE
AS
BEGIN
SELECT * FROM DELETED
SELECT* FROM INSERTED 
END